traffic/config/routes.rb
Rails.application.routes.draw do
  
  resources :junctions

  get '/next', to: 'junctions#next'

  root 'welcome#index'

end

traffic/app/models/junction.rb
# require './lib/traffic_light'

class Junction < ActiveRecord::Base
  
  has_many :traffic_lights, dependent: :destroy

  validates :title, presence: true
  validates :lights, presence: true,
                     numericality: { only_integer: true,  
                     greater_than: 1, 
                     less_than: 5 }

  # Used to initiate cycle! from browser
  def cycle= input
    if input == '1'
      cycle!
    end
  end


  # Cycles all lights to next step simultaneously
  def cycle!
    traffic_lights.each { |light| 
      puts light
      puts light.red  
      light.change }
  end

  # Returns correct CSS code for a given light
  def light_up no, colour
    case true
    when traffic_lights[no].state == 'Green'
      if colour == 'Green'
        "green_circle"
      else
        "grey_circle"
      end
    when traffic_lights[no].state == 'Red'
      if colour == 'Red'
        "red_circle"
      else
        "grey_circle"
      end
    when traffic_lights[no].state == 'Orange'
      if colour == 'Orange'
        "orange_circle"
      else
        "grey_circle"
      end
    when traffic_lights[no].state == 'RedOrange'
      if colour == 'Red'
        "red_circle"
      elsif colour == 'Orange'
        "orange_circle"
      else
        "grey_circle"
      end
    else
      'Error'
    end
  end

end

traffic/app/models/traffic_light.rb
class TrafficLight < ActiveRecord::Base
  belongs_to :junction

  # Functions to change (!) and check (?) individucal lights
  def red!
    if red == false
      puts "/R"
      update red: true
    else
      puts "R"
      update red: false
    end
  end

  def red?
    red
  end

  def orange!
    if orange == true
      update orange: false
    else
      puts "O"
      update orange: true
    end
  end

  def orange?
    orange
  end

  def green!
    if green == true
      update green: false
    else
      puts "G"
      update green: true
      puts green
    end
  end

  def green?
    green
  end

  # Changes the lights to the next arrangement in the sequence
  def change
    case true
    #  Red to Red & Orange
    when red? && !orange? && !green?
      orange!  
    # Red & Orange to Green
    when red? && orange? && !green?
      red! 
      orange! 
      green! 
    # Green to Orange
    when !red? && !orange? && green?
      orange!
      green!
    # Orange to Red
    when !red? && orange? && !green?
      red! 
      orange! 
    # If illegal setup  
    else
      puts 'Error, please Reset'
    end
  end

  # returns a clear written output of which lights are on
  def state
    # colour_set.select {|sym| send(sym) }
    case true
    #  Red
    when red? && !orange? && !green?
      'Red'  
    # Red & Orange
    when red? && orange? && !green?
      'RedOrange'
    # Green
    when !red? && !orange? && green?
      'Green'
    # Orange
    when !red? && orange? && !green?
      'Orange' 
    # If illegal setup  
    end
  end

end

traffic/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

traffic/app/controllers/junctions_controller.rb
class JunctionsController < ApplicationController

  def new
    @junction = Junction.new
  end

  def create
    @junction = Junction.new(junction_params)

    if @junction.save
      @junction.id

      @junction.lights.times do |count| 
        @junction.traffic_lights.create red: true, orange: false, green: false
        if count.even?
          @junction.traffic_lights[count].red!
          @junction.traffic_lights[count].green!
        end
      end
      redirect_to @junction
    else
      render 'new'
    end
  end

  def show
    @junction = Junction.find(params[:id])
  end

  def index
    @junctions = Junction.all
  end

  def edit
    @junction = Junction.find(params[:id])
  end

  def update
    @junction = Junction.find(params[:id])

    if @junction.update(junction_params)
      if request.xhr?
        render js: "window.location.pathname = #{junction_path(@junction.id).to_json}"
      else
        redirect_to @junction
      end
    else
      render 'edit'
    end
  end

  def destroy
    @junction = Junction.find(params[:id])
    @junction.destroy

    redirect_to junctions_path
  end


  private

    def junction_params
      params.require(:junction).permit(:title, :lights, :cycle)
    end

end

traffic/app/controllers/traffic_lights_controller.rb
class TrafficLightsController < ApplicationController

	def create
		@junction = Junction.find(params[:junction_id])
		@traffic_light = @junction.traffic_lights.create(params[:traffic_light])
	end

	def edit
    	@junction = Junction.find(params[:junction_id])
		@traffic_light = @junction.traffic_lights.create(params[:traffic_light])
  	end

  	def update
    	@junction = Junction.find(params[:junction_id])
		@traffic_light = @junction.traffic_lights.create(params[:traffic_light])

	    if @traffic_light.update(params[:traffic_light])
    	  redirect_to @junction
   		else
      	  render 'edit'
    	end
  	end

	def destroy
		@junction = Junction.find(params[:junction_id])
		@traffic_light = @junction.traffic_lights.find(params[:id])
		@traffic_light.destroy
	end

end

traffic/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

traffic/app/helpers/application_helper.rb
module ApplicationHelper
end

traffic/app/helpers/junctions_helper.rb
module JunctionsHelper
end

traffic/app/helpers/traffic_lights_helper.rb
module TrafficLightsHelper
end

traffic/app/helpers/welcome_helper.rb
module WelcomeHelper
end

traffic/app/views/junctions/_form.html.erb
<%= form_for @junction do |f| %>
  <% if @junction.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@junction.errors.count, "error") %> prohibited
      this junction from being saved:</h2>
    <ul>
    <% @junction.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :lights %><br>
    <%= f.text_field :lights %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

traffic/app/views/junctions/edit.html.erb
<h1>Edit Junction</h1>

<%= render 'form' %>

<%= link_to 'Back', junctions_path %>

traffic/app/views/junctions/index.html.erb
<head>

	<style>
	
		table {
			border-collapse: collapse;
		}

	</style>

</head>

<h1>Junction List</h1>

<table>
	<tr>
		<th>Name</th>
		<th>Lights</th>
		<th colspan="3"></th>
	</tr>
	<tr></tr>

	<% @junctions.each do |junc| %>
		<tr>
			<td><%= junc.title %></td>
			<td><%= junc.lights %></td>
			<td><%= link_to 'Show', junction_path(junc) %></td>
			<td><%= link_to 'Edit', edit_junction_path(junc) %></td>
			<td><%= link_to 'Delete', junction_path(junc), method: :delete, data: { confirm: 'Delete Junction?'} %></td> 
		</tr>
	<% end %>
</table>
<br>
<%= link_to 'New Junction', new_junction_path %>

traffic/app/views/junctions/new.html.erb
<h1>New Junction</h1>

<%= render 'form' %>

<%= link_to 'Back', junctions_path %>

traffic/app/views/junctions/show.html.erb
<head>

	<style>

		table {
			border-collapse: collapse;
		}
		table, td, th  {
			border: 1px black;
			text-align: center;
			background-color: white;
			color: white;
			padding: 5px;
				}

		.grey_circle {
			width: 50px;
			height: 50px;
			background: lightgrey;
			-webkit-border-radius: 25px;
			-moz-border-radius: 25px;
			border-radius: 25px;
		}

		.red_circle {
			width: 50px;
			height: 50px;
			background: red;
			-webkit-border-radius: 25px;
			-moz-border-radius: 25px;
			border-radius: 25px;
		}

		.orange_circle {
			width: 50px;
			height: 50px;
			background: orange;
			-webkit-border-radius: 25px;
			-moz-border-radius: 25px;
			border-radius: 25px;
		}

		.green_circle {
			width: 50px;
			height: 50px;
			background: green;
			-webkit-border-radius: 25px;
			-moz-border-radius: 25px;
			border-radius: 25px;
		}

		}

		.set {
			outline-style: solid;
			outline-color: black;
			border-style: solid;
			border-color: black;
		}

		.light {
			background-color: black;
			padding: 10px;
		}

	</style>

	<script>

	// Tells Rails to run junction.cycle! using cycle = 1
	function lightCycle() {
		$.ajax({
			type: 'PUT',
			url: '/junctions/<%= @junction.id %>',
			 data: {junction: {cycle: '1'}},
		     
		});
	}

	</script>

</head>

<body>
<p>
	<strong>Title:</strong>
	<%= @junction.title %><br>
</p>

<table>
	<tr>
		<td></td>
		<td>
			<table class='set'>
				<% ['Red', 'Orange', 'Green'].each do |hue| %> 
				<tr>
					<td class='light'>
						<div class="<%= @junction.light_up(1, hue) %>"></div>
					</td>
				</tr>
				<% end %>
			</table>
		</td>
		<td></td>
	</tr>
	<tr>
		<td><% if @junction.lights > 2 %>
			<table class='set'>
				<% ['Red', 'Orange', 'Green'].each do |hue| %> 
				<tr>
					<td class='light'>
						<div class="<%= @junction.light_up(0, hue) %>"></div>
					</td>
				</tr>
				<% end %>
			</table>
			<% end %></td>
		<td>*</td>
		<td><% if @junction.lights > 2 %>
			<table class='set'>
				<% ['Red', 'Orange', 'Green'].each do |hue| %> 
				<tr>
					<td class='light'>
						<div class="<%= @junction.light_up(2, hue) %>"></div>
					</td>
				</tr>
				<% end %>
			</table>
		<% end %></td>
	</tr>
	<tr>
		<td></td>
		<td>
			<% case true %>
			<% when @junction.lights == 2 %>
				<table class='set'>
				<% ['Red', 'Orange', 'Green'].each do |hue| %> 
				<tr>
					<td class='light'>
						<div class="<%= @junction.light_up(0, hue) %>"></div>
					</td>
				</tr>
				<% end %>
			</table>
			<% when @junction.lights == 4 %>
				<table class='set'>
				<% ['Red', 'Orange', 'Green'].each do |hue| %> 
				<tr>
					<td class='light'>
						<div class="<%= @junction.light_up(3, hue) %>"></div>
					</td>
				</tr>
				<% end %>
			</table>
			<% end %>
		</td>
		<td></td>
	</tr>
</table>
<br>
<button onclick = "lightCycle(); return false;" > Cycle </button>
<br>
<br>
<%= link_to 'Back', junctions_path %>
</body>

traffic/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Traffic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

traffic/app/views/welcome/index.html.erb
<h1>Traffic Light Test Web App</h1>
<%= link_to 'Junctions', controller: 'junctions' %> 